[build]
  command = "flutter config --enable-web && flutter pub get && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "latest"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
